spring.application.name=Inventory Management System

# PostgreSQL connection (Render)
spring.datasource.url=jdbc:postgresql://dpg-d7n2fabbc2fs738ifb00-a:5432/ims_6h9f
spring.datasource.username=ims_6h9f_user
spring.datasource.password=5FieY78S8n4FXzi101tIj8o4JNDdD5T2

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# PostgreSQL dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect